services:
  producer:
    network_mode: host
    build:
      dockerfile: ../dockerfiles/rdkafka-producer.dockerfile
      context: delivery-producer-rs
      args:
        CPUARCH: ${CPUARCH:-x86_64}
  train:
    network_mode: host
    build:
      dockerfile: ../dockerfiles/train.dockerfile
      context: delivery-model-rs
      args:
        CPUARCH: ${CPUARCH:-x86_64}
    volumes:
      - ./delivery-model-rs/model.safetensors:/model.safetensors
  inference:
    build:
      dockerfile: ../dockerfiles/inference-web.dockerfile
      context: delivery-model-rs
    ports:
      - 8000:8000
    volumes:
      - ./delivery-model-rs/model.safetensors:/model.safetensors:ro
